export const ADD_ITEM="ADD_ITEM";
export const DELETE_TASK_ASSIGN="DELETE_TASK_ASSIGN";
export const ADD_IN_PROGRESS="ADD_IN_PROGRESS";
export const DELETE_TASK_IN_PROG="DELETE_TASK_IN_PROG";
export const ADD_IN_COMPLETE="ADD_IN_COMPLETE";